### ISSUE TITLE
Будешь ли ты проектировать плату под клавиатуру?

### ISSUE THREAD

**Issue by grafanaKibana** [seniorsoftwarevlogger/takmak#1]
Будешь ли ты проектировать плату под клавиатуру и делиться?)

**Comment by nLight** [comment]
Уже в пути

![Screenshot 2022-01-31 at 21 52 46](https://user-images.githubusercontent.com/186223/151871274-e4c3bcc3-264b-416d-95c1-a6d40e664473.png)

**Comment by grafanaKibana** [comment]
> Уже в пути
> 
> ![Screenshot 2022-01-31 at 21 52 46](https://user-images.githubusercontent.com/186223/151871274-e4c3bcc3-264b-416d-95c1-a6d40e664473.png)
> 

Можно gerber?)

**Comment by nLight** [comment]
Пока нет. Надо проверить.

**Comment by grafanaKibana** [comment]
Есть какой-то апдейт по этому?)

**Comment by nLight** [comment]
Вариант работает с одним исправлением, но я его уже переделал и надо
проверить новую версию.

**Comment by CoffeeAddictGuy** [comment]
Привет, плохо понимаю в платах
Можешь подсказать, где на плате место для диодов? Всматриваюсь и никак понять не могу(

**Comment by nLight** [comment]
пару примеров указал

![PXL_20221220_211945140](https://user-images.githubusercontent.com/186223/208769373-da277eb0-c844-429e-9641-9ca58efc89f1.jpg)

**Comment by nLight** [comment]
Платы залиты в реп, кстати

**Comment by CoffeeAddictGuy** [comment]
Тогда ещё вопросик, направление диодов любое?
Или в каком направлении их припаивать?
Диоды 1N4742A-12V
![image](https://user-images.githubusercontent.com/31831491/208973520-a4b7379b-616a-438d-9a7f-bd15f9623c0a.png)

**Comment by nLight** [comment]
Черной головкой (катодом) к квадрату.

**Comment by CoffeeAddictGuy** [comment]
Привет, ещё вопрос
Можно ли использовать данные место под подключение LED диодов?
![image](https://user-images.githubusercontent.com/31831491/209466784-3dbdfdcf-cc96-4d3b-8b4b-a8ba1db5ddbf.png)

Я понимаю, что это место под другие типы свитчей, но если я правильно понимаю в теории напряжение там есть и работа диодов должна быть, но насколько это будет корректно не понимаю)

**Comment by nLight** [comment]
LED не предполагались. Это доп отверстия под разные свичи. Поэтому нельзя.
